version: "3.8"

services:
  carichapp:
    build: .
    container_name: carichapp
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]
